### ISSUE TITLE
"About Gsteramer" shouldn't be available in toolbars settings when psimedia is not loaded.

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#304]
triggering this action leads to crash.

**Comment by Ri0n** [comment]
some generic approach for hiding toolbar buttons will be developed later. at least it doesn't crash anymore

**Comment by Neustradamus** [comment]
Please note that since this old ticket, there is a window when we click on "About Gstreamer" -> "psimedia is unavailable"
  PsiMedia plugin is not loaded or not initialized.
  Please check https://github.com/psi-im/psimedia for more details.

Thanks to @Ri0n and @Tehnick.
- https://github.com/psi-im/psi/blob/master/src/mainwin.cpp#L1075
- https://github.com/psi-im/psi/commit/2be3e3307fdbb14e9b922f6fda133ca2885c8908#diff-f4f21e4bd7d971df504e79270a107e5b
- https://github.com/psi-im/psi/commit/1268d4d9f7cf46a3c2b78ac62ea83e27c37f527d#diff-f4f21e4bd7d971df504e79270a107e5b
