### ISSUE TITLE
importing profile from psi+ copies whole home dir

### ISSUE THREAD

**Issue by p5n** [psi-im/psi#343]
While migrating from psi+ 1.2.164 to psi 1.3 psi copies whole home folder into its datadir.

(Archlinux x86_64)

Packages:
- psi+: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/psi-plus
- psi: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/psi

If I manually rename psi+ to psi in .config and in .local/share it starts working without profile import.

**Comment by Ri0n** [comment]
hm never heard about such a problem. I'll take a look on the code.

**Comment by p5n** [comment]
Thank you, at least 2 men on archlinux saw this issue.

**Comment by BiTOk** [comment]
I also have this problem.

**Comment by Vitozz** [comment]
I don't understand why psi starts migrating from psi+. Did you have old psi profile directory ~/.psi in your system? Because there is no built-in migration mechanism from psi+ to psi. Only migration from psi (psi+) version <0.15 to version >0.15.
Since December 2019 profile migration feature was removed as outdated.
Maybe we can close this issue.

**Comment by tehnick** [comment]
> December 2019

Really?

> Maybe we can close this issue.

Yep.

**Comment by Vitozz** [comment]
2019... Funny :) 2018 of course

**Comment by dos1** [comment]
This still happens on 1.5 somehow. For some reason it wants to import a profile even though there was none on this system, and choosing the import option starts to copy the whole home dir into `~/.local/share/psi`.
