### ISSUE TITLE
Certificate has expired, several "Server Authentication" box in few minutes for one XMPP server

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#443]
XXXX: Server Authentication box

The XXXX certificate failed the authenticity test.

Certificate has expired

-> Connect anyway
-> Trust this certificate
-> Details
-> Cancel

https://i.ibb.co/cLcnCZV/psi-server-authentication.png

**Comment by Ri0n** [comment]
I don't get it

**Comment by Neustradamus** [comment]
If the server has expired certificate, you have not several windows if you wait few minutes?
Example: 10 minutes?

**Comment by Ri0n** [comment]
Seems the problem arises because without a confirmation connection timout triggers the reconnect procedure which from its side calls PsiAccount::tls_handshaken(). And the last one shows the certificate dialog when something goes wrong with it.

But accroding to the code, this should not happen.
```
        if (canceler) {
            QObject::connect(canceler, SIGNAL(disconnected()), &errorDialog, SLOT(reject()), Qt::AutoConnection);
            QObject::connect(canceler, SIGNAL(reconnecting()), &errorDialog, SLOT(reject()), Qt::AutoConnection);
        }
```
this means if PsiAccount emits disconnected() or reconnecting() the certificate dialog will be hidden.
