### ISSUE TITLE
Psi sourcecode problem

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#450]
There is a problem with Psi, the Psi sourcecode is not linked to "plugins", "psi-l10n", "psimedia", "libpsi", "jdns", "resources", "qconf", "qhttp", other?

An user (or a maintainer) can not create a real build, only the software but without nothing, no plugins, no languages, etc.

It will be nice to look it for have a perfect Psi XMPP client (one package).

With this, users will have a better user experience.

**Comment by Ri0n** [comment]
"plugins" (brings dependencies) won't be linked. same for psimedia (brings dependencies), resources (those are extra resources and never really required) and qconf (standalone tool should live outside).
libpsi and qhttp are already included as submodules. Yes, qhttp is included just for the case when it's not available as a system library. 
Regarding jdns.. since it's kind of abandoned project I don't want to touch it.

**Comment by Neustradamus** [comment]
Main problems are:
- no languages by default
- no plugins by default

No OTR, no OMEMO, etc.

For user security, no good...

**Comment by Ri0n** [comment]
in fact there is no problem to compile plugins when Psi is installed. On linux it install its headers and other stuff required for plugins compilation. Windows builds are pretty much automated now, so it's not necessary to link plugins as well except one thing - api dependencies. But even for the API deps we have git tags and when they match we know it's compatible. If there is no compatible tag then most likely it's not a release.
The worst thing here is that plugins bring its dependencies. For example if we have kde dependent plugins we have to install kde libs even when Psi doesn't require it. So it may require extra efforts to modify Psi build scripts (cmake/qmake files to configure plugins first) to build just compatible stuff. And it's where I don't see this effort as something rational since there is usually no problem to build plugins outside.

But I can agree about l10n though. @tehnick what do you think?

**Comment by tehnick** [comment]
> An user (or a maintainer) can not create a real build, only the software but without nothing, no plugins, no languages, etc.

Absolutely false statement.

> And how the user can install languages and plugins?

As usual: use package prepared by official or unofficial maintainer or build them himself (herself).

> No 1.4 release for languages, plugins... -> incompatibility with master.

Absolutely false statement. See:
* https://github.com/psi-im/psi-l10n/releases
* https://github.com/psi-im/plugins/releases

**Comment by Neustradamus** [comment]
Sorry, I have not seen before:
- https://github.com/psi-im/psi-l10n/releases
- https://github.com/psi-im/plugins/releases

**Comment by tehnick** [comment]
> in fact there is no problem to compile plugins when Psi is installed.

In fact now plugins may be compiled even without installed Psi...

> Windows builds are pretty much automated now

Our Windows builds already come with all available plugins. It anyone wants to build Psi for Windows manually (s)he should sort out what to do in any case. Our build scripts may be get as example.

> So it may require extra efforts to modify Psi build scripts (cmake/qmake files to configure plugins first) to build just compatible stuff.

cmake based build already allow to choose the list of plugins to build.

>  But even for the API deps we have git tags and when they match we know it's compatible. If there is no compatible tag then most likely it's not a release.

Exactly! Current development model is pretty well documented in [README](https://github.com/psi-im/psi/blob/master/README.md#development). But this should be interesting mostly for developers, because end users are supposed to use released versions of Psi. For users who are not satisfied by classical releases cycle there is Psi+.

> But I can agree about l10n though. @tehnick what do you think?

I think that git repo with translations should **not** be linked with main git repo in any way other than similar git tags. But probable there is sense in adding of these translations into official tarballs with Psi releases which are currently hosted on SourceForge.

**Comment by Neustradamus** [comment]
It is not possible to have directly on other distro than Windows, for example a Psi 1.4 with plugins + languages?

**Comment by Ri0n** [comment]
https://github.com/psi-im/plugins/tree/1.4 same for languages. nothing is impossible.

**Comment by Neustradamus** [comment]
Yes but on distro, there is not a real "psi" 1.4 with plugins and languages.
There can have: a simple "psi", a "psi-plugins", a "psi-l10n"...

**Comment by tehnick** [comment]
@Neustradamus 

>It is not possible to have directly on other distro than Windows, for example a Psi 1.4 with plugins + languages?

I do not understand what do you mean.

App bundles for macOS come with all translations and plugins. In GNU/Linux distros and *BSD systems packages and ports are separate in any case. Some of them support meta-packages for installation of all available packages...

**Comment by tehnick** [comment]
> Yes but on distro, there is not a real "psi" 1.4 with plugins and languages.

What "distro" do you mean?

**Comment by tehnick** [comment]
@Neustradamus If you are talking about GNU/Linux distros than you completely misunderstood their conception.

**Comment by Neustradamus** [comment]
I add this link in this ticket: https://aur.archlinux.org/packages/?O=0&K=psi

**Comment by Neustradamus** [comment]
But on Debian/Ubuntu, psi can have some deps like psi-plugins + psi-l10n.

**Comment by tehnick** [comment]
> But on Debian/Ubuntu, psi can have some deps like psi-plugins + psi-l10n.

Yes, dependencies, recommendations and suggestions are possible in deb packages. And so what?

There is nothing to do from Psi developers side. As for package maintainers they are follow Debian/Ubuntu Policy Manual.

**Comment by Neustradamus** [comment]
If an user install psi, it is psi, psi-plugins, psi-l10n

**Comment by tehnick** [comment]
Yes, and this is normal. Please stop flood here.

**Comment by Neustradamus** [comment]
You can confirm that the problem is when we install psi, there is not psi-plugins, psi-l10n in the same time?
