### ISSUE TITLE
Avatar can be too big in User Tooltip and in vCard Status Tab

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#548]
Avatar can be too big in User Tooltip and in vCard Status Tab:
- https://i.ibb.co/vz2pQSf/psi-vcard-status-tab-big-avatar.png
- https://i.ibb.co/sm2bTSp/psi-user-tooltip-big-avatar.png

Note: Do not change the size in vCard with a click on the Avatar, to have "Photo Preview", full size must be here.

**Comment by tehnick** [comment]
This bug in Psi+ was few versions ago and does not exist anymore.

**Comment by Neustradamus** [comment]
@tehnick: Solved?

Currently I have always with your last build.

Because I have this, since a very long time, many years.

**Comment by tehnick** [comment]
> Psi+ v1.4.1209 (2020-05-10, Psi:478e51fa, Psi+:2170e90, webkit)

@Ri0n avatars from jabber.ru and psi-plus.com account do not fill up such space as shown on your screenshots. But few versions ago they were huge, and one more version before they were extremely small because at that time their size was linked to font size.

In other words: the algorithm for calculating perfect size of avatars was changed many time during last week and now avatars look fine in places shown on your screenshots.

**Comment by Neustradamus** [comment]
@tehnick: I have restarted, I have always the problem with your last Psi+ build.

I have refreshed the vCard... always same problem.

**Comment by Neustradamus** [comment]
@tehnick: Always here today:
- https://i.ibb.co/VY2dvS3/psi-big-avatar-tooltip.png

**Comment by Neustradamus** [comment]
@Ri0n: Thanks, normally fixed with this commit:
- https://github.com/psi-im/psi/commit/a7b19dc6e1bce2b17069eb67cab566957e92a512
