### ISSUE TITLE
Date/Time format for "Time" / "Last Status" and maybe others

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#564]
There is not the option to choice the date/time format:
- https://help.talend.com/reader/3zI67zZ9kaoTVCjNoXuEyw/YHc8JcQYJ7mWCehcQRTEIw
- https://docs.oracle.com/cd/E41183_01/DR/Date_Format_Types.html

Can you add it?

Note: On my machine, it is not ISO-8601.

**Comment by Ri0n** [comment]
I don't understand what you want. 
Qt supports all the format in the world

**Comment by Neustradamus** [comment]
You can see here:
- https://i.ibb.co/qpmH4T6/psi-date-time-format-settings-not-chosen.png

Example, it is not:
- YYYY-MM-DD HH:mm ...

It must be better if user can choose in options.

**Comment by Neustradamus** [comment]
- Last Status / Time in Roster/MUC Room Tab Status of User Info / vCard
- Last Status in tooltip on Contact/User in Roster/MUC Rooms

No problem with history log (Example: 2021-11-08T18:04:25)

**Comment by Ri0n** [comment]
From the quick discussion it seems @Neustradamus want's to change this line
```
QString d = QLocale().toString(lastAvailable(), QLocale::ShortFormat);
```

The point is if we already may change UI language why aren't we able to change time format as well? Sounds legit but not something for common use likely. 
Essentially it means we needs a setting hidden somewhere in options tree which by default gives us `QLocale::ShortFormat` (for example when not given), otherwise we treat the setting as string and use it to format time.
Unfortunately it's impossible to set default time format for currently used locale. So it will be required to patch every single place in the code where `QLocale::FormatType` is used. Or otherwise we need to store output of `QLocale::dateFormat` in some global variable, update it from options and use everywhere we need to stringify time.
