### ISSUE TITLE
Minor UX issues

### ISSUE THREAD

**Issue by stokito** [psi-im/psi#854]
I had warm feelings when saw today the Psi and it looks almost like ten years ago when Ya.Onlne was a thing :) It rocks!
Now I want to report a few issues that I had _as a newcomer_.

0. This is a big confusion between Psi and Psi plus. Also it's hard to google and not so many tutorial and comparison videos. On this level many potential users may lost.
1. Registration of account: When I clicked on server's dropdown the Psi stuck and I had to kill it.
2. Once I used my existing account nothing happened because the Psi is offline by default. This may confuse newcomers.
3. I notices the terminal icon with the XMPP console. It's really good and I'll use it but for an average user this is simply not needed and may be hidden from the toolbar. The Service discovery button needs to be replaced with Join conference.
4. I changed status to `Free for chat` but then appeared annoying window to set a message. I don't need it. Statuses were kind of a public message in old days but now it's not that important.
5. For each contact I see it's client. This is nice but again, may be only confusing. Similarly the client can be removed from a tooltip.
6. I checked plugins:
   1. It's a lot of them and it would be great to add a categories: Games, Utils, Encryption
   2. All the encryption plugins should be enabled by default. Without this regular users will never start using OMEMO.
   3. You can't see a plugin description while you didn't enabled it and clicked on the info button
   4. I guess the `Qip X-Statuses Plugin` can be removed. But maybe there is some XEP for it?
   5. The Attention plugin is probably can be just made as a part of Psi itself. This is an important and useful feature.

**Comment by Ri0n** [comment]
Those all are good points maybe some enthusiasts will split it into subtasks and implement one by one 😏

**Comment by Vitozz** [comment]
Some answers:
0. https://github.com/psi-im/psi/blob/master/README.md#development
1. when you report some bugs, try to describe what version of Psi you are using (psi version + OS name), because often developers have to get the same error to fix it.
2. maybe you haven't enabled the auto-connect checkbox in your account settings. Should it be enabled by default, I don't know.
3. service discovery is still a necessary feature, because many people use it to register in XMPP transports
4. yes, this behavior is deprecated
5. you can disable client icons in the settings
6. about plugins:
- categories are not a bad idea, but it will lead to rewriting the list model to a more complex one and will require adding the category to the json file with subsequent processing of this data by the plugin code and psi itself
- in my opinion, encryption plugins should not be enabled by default. Each user should be personally responsible when enabling them
- in fact, each plugin has a description in the tooltip when hovering over it (psi version from the master branch)
- unfortunately, users from the developer group chat voted not to remove the QIP plugin
- unfortunately, the "attention plugin" does not work as it should on modern systems and should be fixed by someone.

But the initiatives are good and perhaps there will be enthusiasts who want to implement them.

**Comment by Ri0n** [comment]
I agree about enabling encryption plugins by default. At least it should allow to decrypt incoming messages. 
but where to use outgoing encryption it's up to the user. 
I would suggest to keep it off make MAM working and enable in 2 cases: 1) user explicitly enabled it for specific chat 2) incoming is encrypted (so the other side wants encrypted chat)

**Comment by Ri0n** [comment]
switching to qxmpp is not easy.  requires a lot of work

**Comment by Neustradamus** [comment]
@stokito: A long time ago, I have already proposed to @Ri0n to switch to QXmpp...
